---
groups:
-
  name: generic
  rules:
  -
    alert: offline
    expr: up == 0
    for: 1m
    annotations:
      summary: >-
        {{ $labels.instance }}: offline
      description: |
        {{ $labels.job }} / {{ $labels.instance }} has been unreachable for more than 1 minute.
    labels:
      instance: '{{ $labels.instance }}'
      severity: critical
  -
    alert: high cpu load
    expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
    for: 0m
    annotations:
      summary: >-
        {{ $labels.instance }}: high cpu load
      description: |
        {{ $labels.job }} / {{ $labels.instance }} has a cpu load of {{ $value }}%
    labels:
      instance: '{{ $labels.instance }}'
      severity: warning
